version: '3.4'

services:
  db:
    image: postgres:latest
    environment:
    - POSTGRES_PASSWORD=postgres
    ports:
    - 5432:5432
   
  phonebook:
    image: phonebook
    build:
      context: ./
      dockerfile: Dockerfile
    links:
      - db
    depends_on:      
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
    ports:
      - 8181:80
